### ISSUE TITLE
Compliments ✨ 

### ISSUE THREAD

**Issue by joe-dev-public** [fac24/week6-asmahan-hallie-peter-maria#32]
- Nice use of product categories!
  - Foreign key in DB :)
  - /categories/id route
  - Good UX to help users find what they're looking for
- Lovely logo 👀 (and generally nice clean aesthetic :)
- Good job getting ElephantSQL set up and working (presumably! I don't have any way to check, other than that your deployed site seems to work :)) 🐢

**Comment by HusJAW** [comment]
another thing to add is you have a well structured project, easy to navigate the code

**Comment by mariaalouisaa** [comment]
Ta very much
