### ISSUE TITLE
Minor script issues - maybe you're not using it? :)

### ISSUE THREAD

**Issue by joe-dev-public** [fac24/week6-asmahan-hallie-peter-maria#33]
This \q is maybe a typo? (I think it'll break the script, which probably has to start with ``#! /bin/sh``.)

https://github.com/fac24/week6-asmahan-hallie-peter-maria/blob/379638ea9618edef67e5fd8fea2f9de95ef9dffd/scripts/create_db#L1

Note the ``example``, and consider changing it before you use the script yourself 🙂 

https://github.com/fac24/week6-asmahan-hallie-peter-maria/blob/379638ea9618edef67e5fd8fea2f9de95ef9dffd/scripts/create_db#L8

Note the ``.env``: if this is the filename you're using for your local environment variable file (which might contain secrets), then that's fine, but you can change this line if you want to use a different filename. (For example, ``create-next-app`` makes a ``.gitignore`` which ignores any files called ``.env.local`` by default.)

https://github.com/fac24/week6-asmahan-hallie-peter-maria/blob/379638ea9618edef67e5fd8fea2f9de95ef9dffd/scripts/create_db#L18

Finally, don't forget that if you *do* change the filename from ``.env`` to something else, you'll also want to edit this line in the other script:

https://github.com/fac24/week6-asmahan-hallie-peter-maria/blob/379638ea9618edef67e5fd8fea2f9de95ef9dffd/scripts/populate_db#L7

**Comment by mariaalouisaa** [comment]
Good spot, thanks!!
