### ISSUE TITLE
move up NextJs Head component  to line 13 to improve readability.

### ISSUE THREAD

**Issue by HusJAW** [fac24/week6-asmahan-hallie-peter-maria#38]
https://github.com/fac24/week6-asmahan-hallie-peter-maria/blob/6e30df11f3c4e94537d3c0ee6e25280ac3103984/components/layout.js#L21

maybe move up NextJs Head component  to line 13 to improve readability.

**Comment by mariaalouisaa** [comment]
noted and done!
